### ISSUE TITLE
Missile will not fire while thrusting + turning left with K_space event set to KEYDOWN

### ISSUE THREAD

**Issue by raedeus** [worhan/pygame-ricerocks-clone#11]
Hello there,

I've been working with this source and have felt that firing missiles with a KEYUP event just didn't feel, well, "shootie" like, so I assigned the K_space event to KEYDOWN. Upon doing this the spaceship has an interesting behaviour:

The ship will shoot while:

Turn left : no thrust
Turn right : no thrust
Turn right : thrust

The ship will NOT shoot while:

Turn left : thrust.

I've been going over the code to try and figure out why this is. Any possibility you, the master coder, could help with this?

Thanks and cheers!

**Comment by raedeus** [comment]
I have discovered that assigning different keys for thrust and turn (WASD) in place of the arrow and space keys has solved this issue. 

W: Thrust
A: Turn left
D: Turn Right
J: Shoot (I suspect any other combination other than arrows and space)

I tested on a different machine and keyboard and the issue with the arrows and space persisted, interestingly enough, in reverse. I could not turn RIGHT and shoot at the same time with the arrow key assignment.

An odd behavior to look into but the above mentioned is a decent workaround.

Thanks and cheers!

**Comment by worhan** [comment]
Hey there, thanks for your interest. Sorry I didn't have time to respond, I did this a long time ago, and currently sitting on a business trip far away from home and don't have time for Python. If you want to contribute your solution to the problem, feel free :)

**Comment by raedeus** [comment]
No worries, worhan. I could not for the life of me figure out a solution
other than a key re-assignment, which I have shared. I will be moving on to
incorporating joystick control (DS4 + pygame.joystick = works great) and
multiplayer support for an Asteroids style battle royale. It may just be
the first code I throw up on Git.

Thanks again and I hope your business trip went well!

Cheers!

raedeus
